# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    csrf_protection: true # Enable CSRF protection
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    fragments: true
    http_method_override: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
