security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            lazy: true # Allow lazy loading for unauthenticated users
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_test
                always_use_default_target_path: false # Redirect to requested page if not explicitly defined
            logout:
                path: app_logout
                target: app_login

        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true # Allow lazy loading
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_test # Redirect after login
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/test2, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
