name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/adam/space-universal
            echo "Switching to SSH remote..."
            git remote set-url origin git@github.com:deathfal/space-universal.git
            echo "Current remote URL:"
            git remote -v
            echo "Fetching updates..."
            git fetch origin master
            echo "Resetting to origin/master..."
            git reset --hard origin/master
            
            # Fix permissions
            echo "Fixing permissions..."
            sudo chown www-data:www-data -R .
            sudo find . -type f -exec chmod 644 {} \;
            sudo find . -type d -exec chmod 755 {} \;
            sudo chmod -R 777 var/
            sudo chmod -R 777 public/
            
            # Build and start containers
            docker compose build apache
            docker compose up -d apache database mailer
            
            # Clear cache and warmup
            echo "Clearing cache..."
            docker compose exec -T apache php bin/console cache:clear
            docker compose exec -T apache php bin/console cache:warmup
            echo "Loading fixtures..."
            docker compose exec -T apache php bin/console doctrine:fixtures:load

